#!/bin/bash

case "$1" in
    lock)
        ~/.config/i3/scripts/lock_screen
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend | ~/.config/i3/scripts/lock_screen
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systelctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
